In [9]:
import numpy as np

L = np.random.rand(20)
L

array([0.57729601, 0.2809288 , 0.05140198, 0.40681106, 0.46758215,
       0.26337749, 0.5023616 , 0.40064446, 0.47431738, 0.05807318,
       0.70005671, 0.42273064, 0.91727302, 0.77745334, 0.9496391 ,
       0.82344881, 0.45056234, 0.66957984, 0.91398948, 0.53240024])

In [15]:
L.sort()
L

array([0.05140198, 0.05807318, 0.26337749, 0.2809288 , 0.40064446,
       0.40681106, 0.42273064, 0.45056234, 0.46758215, 0.47431738,
       0.5023616 , 0.53240024, 0.57729601, 0.66957984, 0.70005671,
       0.77745334, 0.82344881, 0.91398948, 0.91727302, 0.9496391 ])

In [19]:
np.flip(L)

array([0.9496391 , 0.91727302, 0.91398948, 0.82344881, 0.77745334,
       0.70005671, 0.66957984, 0.57729601, 0.53240024, 0.5023616 ,
       0.47431738, 0.46758215, 0.45056234, 0.42273064, 0.40681106,
       0.40064446, 0.2809288 , 0.26337749, 0.05807318, 0.05140198])

In [10]:
LL = [ (i,L[i]) for i in range(len(L))]
LL

[(0, 0.5772960118032873),
 (1, 0.2809287985164173),
 (2, 0.05140197511622868),
 (3, 0.40681106081873575),
 (4, 0.4675821533006881),
 (5, 0.26337748994553745),
 (6, 0.5023616042856488),
 (7, 0.4006444620443086),
 (8, 0.4743173839140704),
 (9, 0.05807317637157772),
 (10, 0.7000567102708702),
 (11, 0.42273064070685074),
 (12, 0.9172730241594714),
 (13, 0.7774533409396358),
 (14, 0.9496391020216651),
 (15, 0.8234488098653842),
 (16, 0.45056233585933736),
 (17, 0.6695798369362923),
 (18, 0.9139894773052747),
 (19, 0.5324002442977712)]

In [13]:
LL.sort(key=lambda x: x[1])

In [21]:
np.flip(L)[0:5]

array([0.9496391 , 0.91727302, 0.91398948, 0.82344881, 0.77745334])

In [22]:
L

array([0.05140198, 0.05807318, 0.26337749, 0.2809288 , 0.40064446,
       0.40681106, 0.42273064, 0.45056234, 0.46758215, 0.47431738,
       0.5023616 , 0.53240024, 0.57729601, 0.66957984, 0.70005671,
       0.77745334, 0.82344881, 0.91398948, 0.91727302, 0.9496391 ])

In [33]:
colors = [ "Gainsboro",
           "Gamboge",
           "Glossy grape",
           "Gold (metallic)",
           "Gold (Crayola)",
           "Golden poppy",
           "Golden yellow",
           "Goldenrod",
           "Gotham green",
           "Granite gray",
           "Granny Smith apple",
           "Gray (web)",
           "Gray (X11 gray)",
           "Green",
           "Green (Crayola)",
           "Green (web)",
           "Green (Munsell)",
           "Green (pigment)",
           "Green-blue",
           "Green Lizard"
           ]

M = np.random.rand(20)
M


array([0.54271742, 0.08356579, 0.84459914, 0.31623228, 0.83783749,
       0.08603638, 0.58023307, 0.73584079, 0.48756939, 0.15952226,
       0.49337045, 0.50012207, 0.83147688, 0.19603904, 0.56062997,
       0.2623    , 0.12932203, 0.53814636, 0.26040894, 0.51886249])

In [34]:
MM = [ (i,M[i]) for i in range(len(M)) ]
MM

[(0, 0.5427174230907871),
 (1, 0.08356578675164472),
 (2, 0.8445991409147532),
 (3, 0.3162322837557817),
 (4, 0.8378374910762032),
 (5, 0.08603638182768714),
 (6, 0.5802330689338201),
 (7, 0.7358407928154617),
 (8, 0.48756938882888645),
 (9, 0.1595222604249248),
 (10, 0.4933704534494878),
 (11, 0.5001220683132755),
 (12, 0.8314768835810168),
 (13, 0.19603903842858328),
 (14, 0.5606299700383907),
 (15, 0.2623000018631262),
 (16, 0.12932203084493898),
 (17, 0.5381463621629631),
 (18, 0.2604089399287458),
 (19, 0.5188624872343434)]

In [37]:
 MM.sort( key = lambda x: -x[1] )
 MM[0:5]

[(2, 0.8445991409147532),
 (4, 0.8378374910762032),
 (12, 0.8314768835810168),
 (7, 0.7358407928154617),
 (6, 0.5802330689338201)]

In [38]:
[ (colors[i],m) for (i,m) in MM[0:5] ]

[('Glossy grape', 0.8445991409147532),
 ('Gold (Crayola)', 0.8378374910762032),
 ('Gray (X11 gray)', 0.8314768835810168),
 ('Goldenrod', 0.7358407928154617),
 ('Golden yellow', 0.5802330689338201)]

In [41]:

M = np.array([0.54271742, 0.08356579, 0.84459914, 0.31623228, 0.83783749,
       0.08603638, 0.58023307, 0.73584079, 0.48756939, 0.15952226,
       0.49337045, 0.50012207, 0.83147688, 0.19603904, 0.56062997,
       0.2623    , 0.12932203, 0.53814636, 0.26040894, 0.51886249])

MMM = list(zip(colors,M))
MMM

[('Gainsboro', 0.54271742),
 ('Gamboge', 0.08356579),
 ('Glossy grape', 0.84459914),
 ('Gold (metallic)', 0.31623228),
 ('Gold (Crayola)', 0.83783749),
 ('Golden poppy', 0.08603638),
 ('Golden yellow', 0.58023307),
 ('Goldenrod', 0.73584079),
 ('Gotham green', 0.48756939),
 ('Granite gray', 0.15952226),
 ('Granny Smith apple', 0.49337045),
 ('Gray (web)', 0.50012207),
 ('Gray (X11 gray)', 0.83147688),
 ('Green', 0.19603904),
 ('Green (Crayola)', 0.56062997),
 ('Green (web)', 0.2623),
 ('Green (Munsell)', 0.12932203),
 ('Green (pigment)', 0.53814636),
 ('Green-blue', 0.26040894),
 ('Green Lizard', 0.51886249)]

In [43]:
MMM.sort(key=lambda x: -x[1])
MMM[0:5]

[('Glossy grape', 0.84459914),
 ('Gold (Crayola)', 0.83783749),
 ('Gray (X11 gray)', 0.83147688),
 ('Goldenrod', 0.73584079),
 ('Golden yellow', 0.58023307)]