In [4]:
import numpy as np

def sbv(index,size):
    return np.array([1.0 if i == index else 0.0 for i in range(size)])


sbv(3,15)

array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
m = np.array([sbv(3,5)-sbv(2,5)])
m

array([[ 0.,  0., -1.,  1.,  0.]])

In [15]:
u,s,vh = np.linalg.svd(m)
u

array([[-1.]])

In [16]:
vh

array([[ 0.        ,  0.        ,  0.70710678, -0.70710678,  0.        ],
       [ 0.        ,  1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.70710678,  0.        ,  0.5       ,  0.5       ,  0.        ],
       [-0.70710678,  0.        ,  0.5       ,  0.5       ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  1.        ]])

In [21]:
aa = { 'a': 1,
       'b': 2,
       'c': -3
     }

keys = list(aa.keys())
keys


['a', 'b', 'c']

In [27]:
objective = sum([ aa[k]*sbv(keys.index(k),len(keys)) for k in keys ])

In [28]:
objective

array([ 1.,  2., -3.])